#!/bin/sh
# shellcheck disable=3010

# Script untuk login otomatis di jaringan wifi.id dan WMS
# Oleh: KopiJahe (https://kopijahe.my.id)

# shellcheck disable=SC1091
# Muat library network OpenWrt
. /lib/functions/network.sh

# Buat berkas baru untuk menyimpan konfigurasi autologin
touch /etc/config/kopijahe

# variabel advancedmode="true" adalah penanda agar
# fungsi loop autologin tidak dijalankan

versi() {
	# Fungsi versi aplikasi
	# Tentukan versi dengan mengubah variabel "ver"
	ver="1.9.2"
}

bantuan() {
	versi
	echo "Aplikasi autologin KopiJahe"
	echo "http://kopijahe.my.id/"
	echo "Versi aplikasi: $ver"
	echo ""
	echo "Penggunaan: kopijahe [-b] [-i] [-u \"<username>\"] [-p \"<password>\"] [-l \"<yes|no>\"] [-c \"<provider>\"] [-v \"<varian>\"] [-m <nomor urut autologin>] [-a]"
	echo "-a: deteksi otomatis jaringan wifi.id atau wms dan turunannya (harus dalam keadaan terkoneksi namun logout dari jaringan)"
	echo "-b: unduh versi script terbaru"
	echo "-c: masukkan penyedia layanan cek captive portal dengan 2 tanda kutip"
	echo "-d: masukkan URL halaman landing (bisa digunakan sebagai pengganti opsi \"-a\" jika deteksi otomatis tidak berhasil)"
	echo "-f: masukkan berkas login_file.txt dengan 2 tanda kutip (misal: \"\etc\login_file.txt\")"
	echo "-h: tampilkan halaman ini"
	echo "-i: instalasi aplikasi autologin"
	echo "-k: matikan semua proses autologin KopiJahe"
	echo "-l: konfigurasi load-balance, diisi \"yes\" atau \"no\", lalu masukkan interface yang akan digunakan (misal: wwan, wwan1)"
	echo "-s: masuk mode auto-reconnect seamless"
	echo "-t: tes dan tampilkan semua konfigurasi aplikasi"
	echo "-u: masukkan username yang digunakan untuk login dengan 2 tanda kutip"
	echo "-m: multi-autologin, masukkan angka jumlah autologin akan yang digunakan"
	echo "-o: lakukan logout secara manual (supaya akun tidak tersangkut)"
	echo "-p: masukkan password yang digunakan untuk login dengan 2 tanda kutip"
	echo "-v: masukkan varian jaringan wifi yang digunakan dengan 2 tanda kutip"
	echo "-w: masukkan lama waktu pengulangan dalam satuan detik (default: 10 detik)"
	echo "-x: masuk ke mode debug (untuk keperluan analisa jika gagal autologin)"
	echo "-z: lakukan login secara manual (untuk keperluan analisa jika gagal autologin)"
	echo ""
	echo "Varian jaringan yang didukung:"
	echo "\"wifi.id\", \"wms\", \"wms-lite\", \"kampus\", \"smartbisnis\""
	echo ""
	echo "Penyedia layanan cek captive portal yang didukung:"
	echo "\"kopijahe\" (default), \"firefox\", \"google\", \"apple\", \"microsoft\", \"xiaomi\", "
	echo ""
	echo "=========================================================================="
	echo ""
	echo "Contoh penggunaan:"
	echo ""
	echo "Penggunaan untuk 1 autologin (deteksi otomatis URL halaman landing):"
	echo "kopijahe -l \"no\" -u \"halo@kopijahe.my.id\" -p \"en4kbang3t\" -v \"wifi.id\" -a"
	echo ""
	echo "Penggunaan untuk 1 autologin (masukkan manual URL halaman landing):"
	echo "kopijahe -l \"no\" -u \"halo@kopijahe.my.id\" -p \"en4kbang3t\" -v \"wifi.id\" -d"
	echo ""
	echo "Penggunaan untuk 2 autologin:"
	echo "kopijahe -m 1 -l \"yes\" -u \"halo@kopijahe.my.id\" -p \"en4kbang3t\" -v \"smartbisnis\" -a" 
	echo "kopijahe -m 2 -l \"yes\" -u \"hola@kopijahe.my.id\" -p \"n1kmats3kali\" -v \"smartbisnis\" -a"
	echo ""
	echo "Penggunaan untuk 1 auto-reconnect seamless:"
	echo "kopijahe -l \"no\" -s"
	echo ""
	echo "Penggunaan dengan berkas tangkapan login CURL via Google Chrome (login_file.txt):"
	echo "kopijahe -l \"no\" -f \"/etc/login_file.txt\""
	echo ""
	echo "Login manual jika autologin gagal (untuk keperluan analisa jika gagal autologin):"
	echo "kopijahe -x -z"
	echo "kopijahe -x -m 1 -z"
	echo "kopijahe -x -m 2 -z"
	exit 0
}

detectconfig() {
	# Fungsi cek pengaturan
	
	# Cek apakah belum ada pengaturan autologin sebelumnya
	# Jika benar, maka:
	# shellcheck disable=SC2102
	if [[ "$advancedmode" = "true" ]] && [[ "$(uci -q show kopijahe.@autologin[$multiautologincfg])" = "" ]]; then
		# Tambahkan pengaturan baru
		uci add kopijahe autologin
	fi
}

osversioncheck() {
	# Fungsi cek versi rilis LEDE/OpenWrt
	osversion="$(grep VERSION_ID /etc/os-release | awk -F'[=]' '{print $2}' | awk -F'[".]' '{print $2}')"
	export osversion
	
	# Jika rilis OpenWrt adalah 14.x atau 15.x, maka beritahu pengguna bahwa versi rilis tidak didukung oleh aplikasi ini
	if [[ "$osversion" = "14" ]] || [[ "$osversion" = "15" ]]; then
		echo "Rilis openwrt di bawah versi 17.01 tidak didukung"
		exit 1
	fi
	
	# Jika digunakan untuk STB (board sunxi), maka anggap versi os sama dengan LEDE 17.01
	# Karena rata-rata STB apabila di-reboot, maka jam akan terpaut jauh daripada dunia nyata
	# Cek board OpenWrt
	openwrt_board="$(grep OPENWRT_BOARD /etc/os-release | awk -F'["=/]' '{print $3}')"
	
	# Jika tidak menggunakan parameter OPENWRT_BOARD, coba parameter LEDE_BOARD
	if [[ "$openwrt_board" = "" ]]; then
		openwrt_board="$(grep LEDE_BOARD /etc/os-release | awk -F'["=/]' '{print $3}')"
	fi 
	
	# Jika digunakan untuk STB (board sunxi), maka anggap versi os sama dengan LEDE 17.01
	if [[ "$openwrt_board" = "sunxi" ]]; then
		osversion="17"
		export osversion
	fi
}

randommaccheck() {
	# Jika tidak terdeteksi perangkat memiliki MAC address acak, maka:
	if [[ "$detectrandommac" = "" ]]; then
		# Tentukan MAC address dari berkas pengaturan
		clientmac="$(uci -q get kopijahe.@autologin["$multiautologinnum"].clientmac)"
	# Jika terdeteksi MAC address acak, maka:
	else
		# Tentukan MAC address dari hasil ifconfig
		clientmac="$(ifconfig "$wandevice" | grep HWaddr | awk -F'[ ]' '{print $10}')"
	fi
}

mwan3check() {
	# Fungsi cek mwan3
	# Untuk mengecek apakah mwan3 terpasang atau tidak
	
	checkmwan3="$(mwan3 --help 2> /dev/null)"
	
	# Jika perintah sebelumnya menghasilkan kode 127, maka
	if [[ "$?" = "127" ]]; then
		# Tentukan bahwa mwan3 tidak terpasang
		checkmwan3="no"
	# Jika tidak, maka:
	else
		# Tentukan bahwa mwan3 terpasang
		checkmwan3="ok"
	fi
	
	# Jika mwan3 terpasang, cek juga apakah mwan3 yang terpasang memiliki fungsi "use" atau tidak
	
	if [[ "$checkmwan3" = "ok" ]]; then
		checkmwan3use="$(mwan3 use 2> /dev/null)"
	fi
	
	if [[ "$checkmwan3use" = "no command specified for mwan3 use" ]]; then
		# Tentukan bahwa mwan3 memiliki fungsi "use"
		checkmwan3use="ok"
	else
		# Tentukan bahwa mwan3 tidak memiliki fungsi "use"
		checkmwan3use="no"	
	fi
}

multiautologin() {
	# Fungsi multi-autologin
	# Tentukan nomor konfigurasi yang akan digunakan
	# sesuai dengan input dari pengguna
	#
	# Jika tidak ada input dari pengguna, atau
	# input tidak valid (nol, atau bukan angka), maka:
	if [[ "$inputmultiautologin" = "0" ]] || [[ "$inputmultiautologin" = "" ]]; then
		# Tentukan bahwa konfigurasi pertamalah
		# yang akan dipakai
		inputmultiautologin="1"
	fi
	# Karena urutan konfigurasi dimulai dari angka 0
	# maka, kurangi hasil dari input pengguna
	multiautologincfg="$((inputmultiautologin-1))"
	detectconfig
	
	# shellcheck disable=SC2102
	if [[ "$(uci -q get kopijahe.@autologin[$multiautologincfg].multi_autologin)" = "" ]]; then
		uci set kopijahe.@autologin["$multiautologincfg"].multi_autologin="$multiautologincfg"
		uci commit kopijahe
	fi
	
	# shellcheck disable=SC2102
	multiautologinnum="$(uci -q get kopijahe.@autologin[$multiautologincfg].multi_autologin)"
}

install() {
	# Fungsi instalasi aplikasi
	# Beritahu pengguna bahwa proses instalasi dimulai
	advancedmode="true"
	multiautologin
	versi
	echo "Memasang Autologin KopiJahe..."
	# Kopi berkas ke folder /usr/bin/
	cp -f "$0" /usr/bin/kopijahe
	# Beri izin eksekusi
	chmod +x /usr/bin/kopijahe
	# Beritahu pengguna versi autologin saat ini
	echo "Versi aplikasi autologin saat ini: $ver"
	
	# Cek apakah curl sudah tersedia di sistem
	checkcurl="$(curl --version)"
	# Jika hasil cek kosong, berarti curl belum tersedia, maka:
	if [[ "$checkcurl" = "" ]]; then
		# Perbarui daftar aplikasi
		opkg update
		# Unduh dan pasang curl
		opkg install curl
	fi
}

killkopijahe() {
	# Fungsi matikan aplikasi
	advancedmode="true"
	# Cari tahu PID dari semua proses kopijahe (kecuali yang menjalankan fungsi ini), lalu matikan
	pgrep -f "kopijahe" | grep -v "^$$" | xargs kill
}

update() {
	advancedmode="true"
	# Fungsi pembaruan aplikasi autologin
	# Unduh versi terbaru dari github
	# dan letakkan hasilnya di folder /tmp terlebih dahulu
	curl --silent https://raw.githubusercontent.com/kopijahe/wifiid-openwrt/master/scripts/kopijahe -o /tmp/kopijahe-update
	# Lakukan instalasi aplikasi
	sh /tmp/kopijahe-update -i
	# Bersihkan sisa berkas update
	rm /tmp/kopijahe-update
	# Matikan dulu semua proses autologin KopiJahe
	killkopijahe
	# Jalankan kembali proses autologin
	sh /etc/rc.local
}

generaterandomid() {
	# Buat 2 pasang karakter acak untuk keperluan login di jaringan WMS
	randomid="$(head -4 /dev/urandom | tr -dc "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" | head -c4)"
}

detectwan() {
	# Deteksi perangkat jaringan WAN yang akan digunakan untuk login
	# Cek terlebih dahulu apakah menggunakan load-balance atau tidak, jika iya, maka:
	if [[ "$(uci -q get kopijahe.@autologin["$multiautologinnum"].loadbalance)" = "yes" ]]; then
		# Dapatkan konfigurasi perangkat dari berkas konfigurasi
		waninterface="$(uci -q get kopijahe.@autologin["$multiautologinnum"].waninterface)"
	# Jika tidak, maka:
	else
		# Catat di konfigurasi bahwa tidak ada load-balance
		uci set "kopijahe.@autologin[$multiautologinnum].loadbalance=no"
		# Simpan konfigurasi
		uci commit
		# Bersihkan cache jaringan terlebih dahulu
		network_flush_cache
		# Cari tahu interface WAN yang digunakan
		network_find_wan waninterface
	fi
	# Tentukan perangkat WAN yang digunakan sesuai dengan hasil di atas
	wandevice="$(ifstatus "$waninterface" | jsonfilter -e '@["device"]')"
	# Tentukan alamat IP yang digunakan sesuai dengan hasil di atas
	iprouter="$(ifstatus "$waninterface" | jsonfilter -e '@["ipv4-address"][0].address')"
}

detecturl() {
	# Fungsi deteksi URL halaman login
	
	# Deteksi URL login dengan cara melihat jawaban redirect dari halaman periksa koneksi
	deteksi="$(curl -k -I --silent --interface "$wandevice" --max-redirs 1 --connect-timeout 10  "http://periksakoneksi.kopijahe.my.id/cek" | grep "Location")"
	
	# Jika gagal mendeteksi menggunakan teknik di atas, maka:
	if [[ "$deteksi" = "" ]]; then
		# Deteksi URL login dengan cara melihat URL landing di halaman redirect
		urllanding="$(curl -k -I --silent --interface "$wandevice" --max-redirs 1 --connect-timeout 10  "http://periksakoneksi.kopijahe.my.id/cek" | grep URL | awk -F'[;]' '{print $2}' | head -c -3)"
		deteksi=" Location: $urllanding"
	fi
}

setup() {
	# Fungsi penyiapan berkas konfigurasi autologin
	advancedmode="true"
	# Deteksi tipe login (hasil "login" = wifi.id, hasil "wms" = wms)
	tipelogin="$(echo "$deteksi" | awk -F'[=&]' '{print $1}' | awk -F'[=/]' '{print $4}')"
	# Deteksi variabel gw_id
	gwid="$(echo "$deteksi" | awk -F'[=&]' '{print $2}')"
	# Deteksi MAC address yang digunakan
	clientmac="$(echo "$deteksi" | awk -F'[=&]' '{print $4}')"
	# Deteksi variabel wlan_id
	wlanid="$(echo "$deteksi" | awk -F'[=&]' '{print $6}')"
	# Deteksi variabel session_id, filter hasilnya agar tidak ada error
	session_id="$(echo "$deteksi" | awk -F'[=&]' '{print $8}' | tr -dc "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-")"
	# Deteksi variabel server_id
	server_id="$(echo "$deteksi" | awk -F'[/]' '{print $3}')"
	# Masukkan konfigurasi sesuai dengan hasil di atas dan sesuai dengan nomor konfigurasi multi-autologin
	uci set kopijahe.@autologin["$multiautologinnum"].tipelogin="$tipelogin"
	uci set kopijahe.@autologin["$multiautologinnum"].gwid="$gwid"
	uci set kopijahe.@autologin["$multiautologinnum"].clientmac="$clientmac"
	uci set kopijahe.@autologin["$multiautologinnum"].wlanid="$wlanid"
	uci set kopijahe.@autologin["$multiautologinnum"].sessionid="$session_id"
	uci set kopijahe.@autologin["$multiautologinnum"].serverid="$server_id"
	
	# Jika digunakan di jaringan WMS, maka tentukan variabel wms_id
	if [[ "$tipelogin" = "wms" ]]; then
		url_landing="$(echo "$deteksi" | awk -F'[ ]' '{print $2}')"
		wms_id="$(echo "$url_landing" | xargs curl -k --silent -L --interface "$wandevice" | grep username_hidden | awk -F'[.]' '{print $4}' | awk '!a[$0]++' | tr -dc "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")"
		uci set kopijahe.@autologin["$multiautologinnum"].wmsid="$wms_id"
	fi
	
	# Simpan konfigurasi
	uci commit kopijahe
}

loginblock() {
	# Fungsi cek blokir login
	# Buat berkas "/tmp/last.login.$waninterface" untuk menghindari error
	touch "/tmp/last.login.$waninterface"
	
	# Jika di dalam berkas ditemukan hasil "Bloked IP", maka:
	if [[ "$(grep -o "Blocked IP" "/tmp/last.login.$waninterface")" = "Blocked IP" ]]; then
		# Tentukan bahwa IP diblokir
		ipblocked=yes
	# Jika tidak ditemukan, maka:
	else
		# Tentukan bahwa IP tidak diblokir
		ipblocked=no
	fi
	
	# Jika di dalam berkas ditemukan hasil "Gagal Login", maka:
	if [[ "$(grep -o "Gagal Login" "/tmp/last.login.$waninterface")" = "Gagal Login" ]]; then
		# Tentukan bahwa login diblokir
		loginblocked=yes
	# Jika tidak ditemukan, maka:
	else
		# Tentukan bahwa login tidak diblokir
		loginblocked=no
	fi
}

refreshinterface() {
	# Matikan perangkat yang digunakan
	ifconfig "$wandevice" down
	# Hidupkan kembali perangkat yang digunakan
	ifconfig "$wandevice" up
	
	# Cek apakah digunakan untuk load-balance dan mwan3 terpasang, jika benar, maka:
	mwan3check
	if [[ "$(uci -q get kopijahe.@autologin["$multiautologinnum"].loadbalance)" = "yes" ]] && [[ "$checkmwan3" = "ok" ]]; then
		# Hidupkan interface tanpa menggunakan mwan3
		ifup "$waninterface"
		# Hidupkan juga interface di mwan3
		mwan3 ifup "$waninterface"
	# Jika tidak, maka:
	else
		# Hidupkan interface tanpa menggunakan mwan3
		ifup "$waninterface"
	fi
	# Reset kode status, supaya tidak terjadi pengulangan
	kodestatus=""
}

releaseobtainnewip() {
	# Fungsi meminta alamat IP baru
	# Cari tahu PID dari layanan DHCP client (udhcpc) yang digunakan
	udhcpcpid="$(cat /var/run/udhcpc-"$wandevice".pid)"
	# Matikan layanan DHCP Client dengan parameter SIGUSR2
	kill -SIGUSR2 "$udhcpcpid"
	
	refreshinterface
}

deviceclaimfailed() {
	# Fungsi deteksi error "DEVICE_CLAIM_FAILED"
	# Cek apakah muncul kode error di status interface
	claimfailed="$(ifstatus "$waninterface" | jsonfilter -e '@["errors"][0].code')"
	
	# Jika muncul kode error "DEVICE_CLAIM_FAILED", maka:
	if [[ "$claimfailed" = "DEVICE_CLAIM_FAILED" ]]; then
		# Perbarui interface
		refreshinterface
	fi
}

sleeptimer() {
	# Fungsi pengaturan waktu pengulangan autologin
	
	sleeptime="$(uci -q get kopijahe.@autologin["$multiautologinnum"].sleeptime)"
	
	# Jika konfigurasi tidak ditemukan, maka:
	if [[ "$sleeptime" = "" ]]; then
		# Masukkan konfigurasi bawaan pengulangan setiap 8 detik 
		uci set "kopijahe.@autologin[$multiautologinnum].sleeptime=8"
		# Simpan konfigurasi
		uci commit kopijahe
		# Tentukan variabel sleeptime ke 8 detik
		sleeptime="8"
	fi	
}

testing() {
	advancedmode="true"
	generaterandomid
	versi
	
	pidkopijahe="$(pgrep -f "kopijahe" | grep -v "^$$")"
	
	echo "Versi aplikasi: $ver"
	echo "" 
	echo "Pengaturan autologin:"
	uci show kopijahe
	echo ""
	echo "random ID: $randomid"
	echo "PID autologin: $pidkopijahe"
}

captiveportalcheck() {
	# Fungsi cek captive portal (halaman login)
	# Tentukan penyedia layanan cek captive portal berdasarkan konfigurasi sebelumnya
	cpcprovider="$(uci -q get kopijahe.@autologin["$multiautologinnum"].cpcprovider)"
	
	# Jika konfigurasi tidak ditemukan, maka:
	if [[ "$cpcprovider" = "" ]]; then
		# Masukkan konfigurasi penyedia layanan KopiJahe sebagai penyedia layanan bawaan
		uci set "kopijahe.@autologin[$multiautologinnum].cpcprovider=kopijahe"
		# Simpan konfigurasi
		uci commit kopijahe
		# Tentukan variabel cpcprovider ke kopijahe
		cpcprovider="kopijahe"
	fi
	
	# Jumlah percobaan ulang cek captive portal
	cpcretry="$(uci -q get kopijahe.@autologin["$multiautologinnum"].cpcretry)"
	
	#	Jika konfigurasi tidak ditemukan, maka:
	if [[ "$cpcretry" = "" ]]; then
		# Masukkan konfigurasi bawaan percobaan ulang 2 kali
		uci set "kopijahe.@autologin[$multiautologinnum].cpcretry=2"
		# Simpan konfigurasi
		uci commit kopijahe
		# Tentukan variabel cpcretry ke 2
		cpcretry="2"
	fi
	
	# Lama timeout cek captive portal
	cpctimeout="$(uci -q get kopijahe.@autologin["$multiautologinnum"].cpctimeout)"
	
	# Jika konfigurasi tidak ditemukan, maka:
	if [[ "$cpctimeout" = "" ]]; then
		# Masukkan konfigurasi bawaan timeout 3 detik
		uci set "kopijahe.@autologin[$multiautologinnum].cpctimeout=3"
		# Simpan konfigurasi
		uci commit kopijahe
		# Tentukan variabel cpcretry ke 3
		cpctimeout="3"
	fi	
	
	# Daftar penyedia layanan cek captive portal beserta hasil cek yang diharapkan
	# 
	# KopiJahe: Layanan cek captive portal bawaan script
	if [[ "$cpcprovider" = "kopijahe" ]]; then
		cekkoneksi="$(curl --interface "$wandevice" -L --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://periksakoneksi.kopijahe.my.id/cek")"
		kodestatuslanding="$?"
		hasil="OK"
	# Firefox: Layanan cek captive portal bawaan browser Mozilla Firefox
	elif [[ "$cpcprovider" = "firefox" ]]; then
		cekkoneksi="$(curl --interface "$wandevice" -L --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://detectportal.firefox.com/success.txt")"
		kodestatuslanding="$?"
		hasil="success"
	# Google: Layanan cek captive portal bawaan sistem operasi android
	elif [[ "$cpcprovider" = "google" ]]; then
		cekkoneksi="$(curl --interface "$wandevice" -LI --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://connectivitycheck.gstatic.com/generate_204" | grep -o "204")"
		kodestatuslanding="$?"
		hasil="204"
	# Apple: Layanan cek captive portal bawaan perangkat Apple
	elif [[ "$cpcprovider" = "apple" ]]; then
		cekkoneksi="$(curl --interface "$wandevice" -L --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://captive.apple.com/" | grep -o "Success" | head -c8)"
		kodestatuslanding="$?"
		hasil="Success"
	# Apple2: Layanan cek captive portal alternatif perangkat Apple
	elif [[ "$cpcprovider" = "apple2" ]]; then
		cekkoneksi="$(curl --interface "$wandevice" -L --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "https://www.apple.com/library/test/success.html" | grep -o "Success" | head -c8)"
		kodestatuslanding="$?"
		hasil="Success"
	# Microsoft2: Layanan cek captive portal alternatif milik Microsoft
	elif [[ "$cpcprovider" = "microsoft2" ]]; then
		cekkoneksi="$(curl --interface "$wandevice" -L --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://www.msftncsi.com/ncsi.txt")"
		kodestatuslanding="$?"
		hasil="Microsoft NCSI"
	# Microsoft: Layanan cek captive portal bawaan sistem operasi Windows
	elif [[ "$cpcprovider" = "microsoft" ]]; then
		cekkoneksi="$(curl --interface "$wandevice" -L --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://www.msftconnecttest.com/connecttest.txt")"
		kodestatuslanding="$?"
		hasil="Microsoft Connect Test"
	# Xiaomi: Layanan cek captive portal bawaan sistem operasi MIUI
	elif [[ "$cpcprovider" = "xiaomi" ]]; then
		cekkoneksi="$(curl --interface "$wandevice" -LI --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://connect.rom.miui.com/generate_204" | grep -o "204")"
		kodestatuslanding="$?"
		hasil="204"
	fi
	
	# Jika hasil cek koneksi sesuai dengan hasil yang diharapkan, maka:
	if [[ "$cekkoneksi" = "$hasil" ]]; then
		# Tentukan bahwa terkoneksi dengan internet
		internetconnected="yes"
	# Jika hasilnya tidak sama, maka:
	else
		# Tentukan bahwa tidak terkoneksi dengan internet
		internetconnected="no"
	fi	
	
	# Jika kode status hasil cek koneksi adalah 127, maka:
	if [[ "$kodestatuslanding" = "127" ]]; then
		# Beritahu pengguna bahwa CURL belum terpasang
		echo "CURL belum perpasang" | logger -t "kopijahe $ver"
		# Lakukan pembaruan daftar aplikasi
		opkg update
		# Lalu unduh dan instal CURL
		opkg install curl
	fi
}

login_folder() {
	# Fungsi penentuan folder dan url login
	# Tentukan variabel server_id untuk dipakai nanti
	server_id="$(uci -q get kopijahe.@autologin["$multiautologinnum"].serverid)"
	# Jika tipe login adalah wifi.id, maka tentukan URL login yang sesuai:
	if [[ "$(uci -q get kopijahe.@autologin["$multiautologinnum"].tipelogin)" = "login" ]]; then
		loginurl="https://$server_id/authnew/login/check_login.php"
	# Jika tipe login adalah wms, maka tentukan URL login yang sesuai:
	elif [[ "$(uci -q get kopijahe.@autologin["$multiautologinnum"].tipelogin)" = "wms" ]]; then
		loginurl="https://$server_id/wms/auth/authnew/autologin/quarantine.php"
	else
	# Jika tipe login tidak diketahui, maka konfigurasi masih belum lengkap, silahkan ulangi deteksi otomatis jaringan
		echo "Ada kesalahan konfigurasi jaringan"
	fi
}

wificommunity() {
	# Tentukan akhiran username sesuai dengan varian jaringan yang dipilih:
	#
	# Jika smartbisnis, maka:
	if [[ "$wifivariant" = "smartbisnis" ]]; then
		# Tentukan akhiran username "@com.smartbisnis"
		username2="$username@com.smartbisnis"
	# Jika kampus:
	elif [[ "$wifivariant" = "kampus" ]]; then
		# Tentukan akhiran username sesuai dengan konfigurasi kampus yang tersimpan
		cfgkampus="$(uci -q get kopijahe.@autologin["$multiautologinnum"].kampus)"
				
		# Jika digunakan untuk akun UT, maka:
		if [[ "$cfgkampus" = "ut.ac.id" ]]; then
			# Akun UT punya format berbeda dibandingkan dengan kampus lainnya
			kampus="$(echo "$cfgkampus" | awk -F'[.]' '{print $1}')"
			username2="$username@$cfgkampus@com.$kampus"
		elif [[ "$cfgkampus" = "adibuana" ]]; then
			# Akun Adibuana punya format berbeda dibandingkan dengan kampus lainnya
			username2="$username@$cfgkampus.vmgmt@wms.00000000.000"
		# Jika bukan akun UT dan adibuana, maka:
		else
			# Jika bukan UT, maka gunakan format standard:
			username2="$username@com.$cfgkampus"
		fi
	# Jika WMS Lite, maka:
	elif [[ "$wifivariant" = "wms-lite" ]] || [[ "$wifivariant" = "wmslite" ]]; then
		generaterandomid
		# Tentukan akhiran username login untuk jaringan WMS Lite
		wmsid="$(uci -q get kopijahe.@autologin["$multiautologinnum"].wmsid)"
		username3="@wmslite.$wmsid.000"
	# Jika WMS, maka:
	elif [[ "$wifivariant" = "wms" ]]; then
		generaterandomid
		# Tentukan akhiran username login untuk jaringan WMS
		wmsid="$(uci -q get kopijahe.@autologin["$multiautologinnum"].wmsid)"	
		username3="@wms.$wmsid.000"
	# Jika wifi.id, maka:
	elif [[ "$wifivariant" = "wifi.id" ]] || [[ "$wifivariant" = "@wifi.id" ]]; then
		# Periksa apakah akun yang digunakan adalah akun violet, jika iya, maka:
		if [[ "$(echo "$username" | awk -F'[@]' '{print $2}')" = "violet" ]]; then
			# Tidak perlu diberi tambahan akhiran
			username2="$username"
		# Jika tidak, maka:
		else
			# Beri tambahan akhiran "@spin2"
			username2="$username@spin2"
		fi
	fi
}

dataraw() {
	# Jika digunakan untuk jaringan @wifi.id umum, maka:
	if [[ "$(uci -q get kopijahe.@autologin["$multiautologinnum"].wifivariant)" = "@wifi.id" ]] || [[ "$(uci -q get kopijahe.@autologin["$multiautologinnum"].wifivariant)" = "wifi.id" ]]; then
		login_cred="username=""$username2""&password=""$password"""
	# Jika digunakan untuk jaringan komunitas, maka:
	elif [[ "$(uci -q get kopijahe.@autologin["$multiautologinnum"].wifivariant)" = "smartbisnis" ]] || [[ "$(uci -q get kopijahe.@autologin["$multiautologinnum"].wifivariant)" = "kampus" ]]; then
		login_cred="username=""$username2""&password=""$password"""
	# Jika digunakan untuk jaringan WMS atau WMS Lite, maka:
	elif [[ "$(uci -q get kopijahe.@autologin["$multiautologinnum"].wifivariant)" = "wms" ]] || [[ "$(uci -q get kopijahe.@autologin["$multiautologinnum"].wifivariant)" = "wms-lite" ]]; then
		login_cred="username_=""$username2""&autologin_time=&username=""$username"".""$randomid""$username3""&password=""$password"""
	fi 
}

hasil_login() {
	# Fungsi output hasil login

	# Filter hasil login hanya di bagian yang relevan saja
	hasillogin="$(echo "$login" | jsonfilter -e '@["message"]' 2> /dev/null)"

	# Jika variabel hasillogin kosong, maka login tidak berhasil
	# Cek apakah mode bypass (parameter -z) hidup, jika tidak, maka:
	if [[ "$hasillogin" = "" ]] && [[ "$bypassmode" = "" ]]; then
		# Laporkan hasil login tidak berhasil, berikut kode status CURL untuk halaman login/landing dan percobaan login
		hasillogin="Login tidak berhasil, kode status CURL: $kodestatuslanding & $kodestatus"
	elif [[ "$hasillogin" = "" ]] && [[ "$bypassmode" = "true" ]]; then
		# Laporkan hasil login tidak berhasil, berikut kode status CURL untuk percobaan login
		hasillogin="Login tidak berhasil, kode status CURL: $kodestatus"
	fi
	
	# Jika digunakan di mode lanjutan, maka:
	if [[ "$advancedmode" = "true" ]]; then
		# Beritahu pengguna melalui layar terminal/stdout
		echo "Percobaan login. Interface: $waninterface. Hasil: $hasillogin"
		# Simpan juga hasilnya di berkas "/tmp/last.login.$waninterface" dan beritahu pengguna melalui System Log
		echo "Percobaan login. Interface: $waninterface. Hasil: $hasillogin" | tee -a "/tmp/last.login.$waninterface" | logger -t "kopijahe $ver"
	# Jika tidak, maka:
	else
		# Simpan hasilnya di berkas "/tmp/last.login.$waninterface" dan beritahu pengguna melalui System Log
		echo "Percobaan login. Interface: $waninterface. Hasil: $hasillogin" | tee -a "/tmp/last.login.$waninterface" | logger -t "kopijahe $ver"
	fi
}

hasil_logout() {
	# Fungsi output hasil login

	# Filter hasil login hanya di bagian yang relevan saja
	hasillogout="$(echo "$logout" | awk -F'[<>]' '{print $5}' 2> /dev/null)"

	# Jika variabel hasillogin kosong, maka login tidak berhasil
	# Cek apakah mode bypass (parameter -z) hidup, jika tidak, maka:
	if [[ "$hasillogout" = "" ]] && [[ "$bypassmode" = "" ]]; then
		# Laporkan hasil login tidak berhasil, berikut kode status CURL untuk halaman login/landing dan percobaan login
		hasillogout="Login tidak berhasil, kode status CURL: $kodestatuslanding & $kodestatus"
	elif [[ "$hasillogout" = "" ]] && [[ "$bypassmode" = "true" ]]; then
		# Laporkan hasil login tidak berhasil, berikut kode status CURL untuk percobaan login
		hasillogout="Login tidak berhasil, kode status CURL: $kodestatus"
	fi
	
	# Jika digunakan di mode lanjutan, maka:
	if [[ "$advancedmode" = "true" ]]; then
		# Beritahu pengguna melalui layar terminal/stdout
		echo "Percobaan logout. Interface: $waninterface. Hasil: $hasillogout"
	fi
	
	# Dan beritahu pengguna melalui System Log
	echo "Percobaan logout. Interface: $waninterface. Hasil: $hasillogout" | logger -t "kopijahe $ver"
}

logout_wifi() {
	# Fungsi login dari pengaturan yang disimpan
	
	login_folder
	versi
		
	# Simpan jam dan tanggal saat ini
	date > "/tmp/last.login.$waninterface"
	
	# Cek versi OS, jika menggunakan LEDE 17.01 atau OpenWrt 18.06
	# Maka perlu menggunakan tambahan parameter -k
	if [[ "$osversion" = "17" ]] || [[ "$osversion" = "18" ]]; then
		curladditionalparameter='-k --silent'
	else
		curladditionalparameter='--silent'
	fi
	
	# Lakukan login sesuai dengan parameter konfigurasi autologin
	logout="$(curl --interface "$wandevice" $curladditionalparameter """https://$server_id/authnew/logout/logoutx.php""" \
	-H "authority: ""$server_id""" \
	-H "accept: application/json, text/javascript, */*; q=0.01" \
	-H "x-requested-with: XMLHttpRequest" \
	-H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4315.5 Safari/537.36" \
	-H "content-type: application/x-www-form-urlencoded; charset=UTF-8" \
	-H "origin: https://logout.wifi.id" \
	-H "sec-fetch-site: same-site" \
	-H "sec-fetch-mode: cors" \
	-H "sec-fetch-dest: empty" \
	-H "referer: https://logout.wifi.id/")"
	
	kodestatus="$?"
	hasil_logout
}

login_wifi() {
	# Fungsi login dari pengaturan yang disimpan
	
	login_folder
	randommaccheck
	versi
	username="$(uci -q get kopijahe.@autologin["$multiautologinnum"].username)"
	username2="$(echo "$username" | awk -F'[@]' '{print $1}')"
	password="$(uci -q get kopijahe.@autologin["$multiautologinnum"].password)"
	tipelogin="$(uci -q get kopijahe.@autologin["$multiautologinnum"].tipelogin)"
	gwid="$(uci -q get kopijahe.@autologin["$multiautologinnum"].gwid)"
	wlanid="$(uci -q get kopijahe.@autologin["$multiautologinnum"].wlanid)"
	session_id="$(uci -q get kopijahe.@autologin["$multiautologinnum"].sessionid)"
	wifivariant="$(uci -q get kopijahe.@autologin["$multiautologinnum"].wifivariant)"
	wificommunity
	dataraw
	
	# Simpan jam dan tanggal saat ini
	date > "/tmp/last.login.$waninterface"
	
	# Cek versi OS, jika menggunakan LEDE 17.01 atau OpenWrt 18.06
	# Maka perlu menggunakan tambahan parameter -k
	if [[ "$osversion" = "17" ]] || [[ "$osversion" = "18" ]]; then
		curladditionalparameter='-k --silent'
	else
		curladditionalparameter='--silent'
	fi
	
	# Lakukan login sesuai dengan parameter konfigurasi autologin
	login="$(curl --interface "$wandevice" $curladditionalparameter """$loginurl""?ipc=""$iprouter""&gw_id=""$gwid""&client_mac=""$clientmac""&redirect=&wlan=""$wlanid""" \
	-H "authority: ""$server_id""" \
	-H "accept: application/json, text/javascript, */*; q=0.01" \
	-H "x-requested-with: XMLHttpRequest" \
	-H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4315.5 Safari/537.36" \
	-H "content-type: application/x-www-form-urlencoded; charset=UTF-8" \
	-H "origin: https://""$server_id""" \
	-H "sec-fetch-site: same-origin" \
	-H "sec-fetch-mode: cors" \
	-H "sec-fetch-dest: empty" \
	-H "referer: https://""$server_id""/""$tipelogin""/?gw_id=""$gwid""&client_mac=""$clientmac""&wlan=""$wlanid""&sessionid=""$session_id""" \
	--data-raw "$login_cred")"
	
	kodestatus="$?"
	hasil_login
}

login_file() {
	# Fungsi login dari berkas tangkapan curl Google Chrome
	# (untuk jaringan wifi selain yang didukung di atas)
	advancedmode="true"
	loginfromfile="true"
	loginwifi=/tmp/login_file.txt
	
	# Hapus semua baris "sleep 10 && kopijahe" jika ditemukan untuk menghindari login bertumpuk
	sed -i "/sleep 10 \&\& kopijahe/d" "/etc/rc.local"
	# Tambahkan 1 baris "sleep 10 && kopijahe -f <login_file.txt> &" sebelum baris "exit 0" agar aplikasi berjalan setelah boot
	sed -i "s/exit 0/sleep 10 \&\& kopijahe \-f $loginfiletxt \&\nexit 0/" "/etc/rc.local"

	while [[ "$loginfromfile" = "true" ]]; do
	# Cek nomor pengaturan terlebih dahulu
	multiautologin
	# Deteksi antarmuka jaringan yang dipakai
	detectwan
	# Cek kondisi antarmuka jaringan yang dipakai
	deviceclaimfailed
	# Deteksi status koneksi
	captiveportalcheck
	# Cek apakah login sebelumnya diblokir atau tidak
	loginblock
	# Buat 4 karakter acak untuk keperluan login WMS
	generaterandomid
	# Cek pengaturan waktu pengulangan
	sleeptimer

	# Jika hasil cek koneksi internet tidak berhasil, maka:
	if [[ "$internetconnected" = "no" ]]; then
		# Cek terlebih dahulu apakah login diblokir atau "koneksi bengong" (kode status CURL error 7)
		# Jika benar, maka:
		if [[ "$loginblocked" = "yes" ]]; then
			# Catat jam dan tanggal saat ini di berkas "/tmp/last.login.$waninterface"
			date > "/tmp/last.login.$waninterface"
			# Catat percobaan login terakhir di berkas "/tmp/last.login.$waninterface"
			echo "Percobaan login terakhir:" >> "/tmp/last.login.$waninterface"
			# Beritahu pengguna bahwa koneksi dengan internet terputus
			echo "Koneksi $waninterface terputus, meminta alamat IP baru" | tee -a "/tmp/last.login.$waninterface" | logger -t "kopijahe $ver"
			# Minta penggantian alamat IP
			releaseobtainnewip
			sleep "$sleeptime"
		# Jika tidak, maka:
		else
			# Catat jam dan tanggal saat ini di berkas "/tmp/last.login.$waninterface"
			date > "/tmp/last.login.$waninterface"
			# Catat percobaan login terakhir di berkas "/tmp/last.login.$waninterface"
			echo "Percobaan login terakhir:" >> "/tmp/last.login.$waninterface"
			# Beritahu pengguna bahwa koneksi dengan internet terputus
			echo "Koneksi $waninterface terputus, meminta alamat IP baru" | tee -a "/tmp/last.login.$waninterface" | logger -t "kopijahe $ver"
			# Gandakan berkas tangkapan login CURL ke tempat proses
			cp "$loginfiletxt" "$loginwifi"
			# Proses berkas autologin
			# Cek versi OS, jika menggunakan LEDE 17.01 atau OpenWrt 18.06
			# Maka perlu menggunakan tambahan parameter -k
			if [[ "$osversion" = "17" ]] || [[ "$osversion" = "18" ]]; then
				sed -i "s/curl/curl -k --silent --interface $wandevice/g" "$loginwifi"
			else
				sed -i "s/curl/curl --silent --interface $wandevice/g" "$loginwifi"
			fi
			sed -i "s/iprouter/$iprouter/g" "$loginwifi"
			sed -i "s/kopijahe/$randomid/g" "$loginwifi"
			# Beri izin eksekusi berkas autologin
			chmod +x "$loginwifi"
			# Lakukan login, lalu simpan hasilnya di berkas "/tmp/last.login.$waninterface" dan beritahu pengguna melalui System Log
			echo "Percobaan login interface: $waninterface" | logger -t "kopijahe $ver"
			$loginwifi | jsonfilter -e '@["message"]' 2> /dev/null | tee -a "/tmp/last.login.$waninterface" | logger -t "kopijahe $ver"
		fi
	fi
	# Istirahat sebelum coba mengecek koneksi kembali
	sleep "$sleeptime"
	done
}

seamless_reconnect() {
	# Fungsi mode reconnect seamless	
	advancedmode="true"
	seamlessreconnectmode="true"
	
	while [[ "$seamlessreconnectmode" = "true" ]]; do
	multiautologin
	detectwan
	captiveportalcheck
	deviceclaimfailed
	
	# Jika hasil cek koneksi internet tidak berhasil, maka:
	if [[ "$internetconnected" = "no" ]]; then
		# Catat jam dan tanggal saat ini di berkas "/tmp/last.login.$waninterface"
		date > "/tmp/last.login.$waninterface"
		# Catat percobaan login terakhir di berkas "/tmp/last.login.$waninterface"
		echo "Percobaan login terakhir:" >> "/tmp/last.login.$waninterface"
		# Beritahu pengguna bahwa koneksi dengan internet terputus
		echo "Koneksi $waninterface terputus, meminta alamat IP baru" | tee -a "/tmp/last.login.$waninterface" | logger -t "kopijahe $ver"
		# Minta penggantian alamat IP
		releaseobtainnewip
		# Tambahan istirahat 10 detik sebelum mengecek ulang
		# sambil menunggu koneksi hidup kembali
		sleep 10
	fi
	# Istirahat selama 10 detik sebelum coba mengecek koneksi kembali
	sleep 10
	done
}

# Cek versi sistem operasi terlebih dahulu
osversioncheck
# Cek juga apakah perangkat tidak punya MAC tetap
detectrandommac="$(dmesg | grep 'generated random MAC address')"

# Fungsi mendapatkan parameter aplikasi
while getopts :abc:df:hkil:m:op:stu:v:w:xz flags
do
	case "${flags}" in
		a)
			multiautologin
			detectwan
			detecturl
			setup
			;;
		b)
			update
			;;
		c)
			icpcprovider="$OPTARG"
			advancedmode="true"
			multiautologin
			if [[ "$icpcprovider" = "kopijahe" ]] || [[ "$icpcprovider" = "firefox" ]] || [[ "$icpcprovider" = "google" ]] || [[ "$icpcprovider" = "apple" ]] || [[ "$icpcprovider" = "apple2" ]] || [[ "$icpcprovider" = "microsoft" ]] || [[ "$icpcprovider" = "microsoft2" ]] || [[ "$icpcprovider" = "xiaomi" ]]; then
				uci set kopijahe.@autologin["$multiautologinnum"].cpcprovider="$icpcprovider"
			else
				echo "Penyedia layanan yang didukung:"
				echo "\"kopijahe\" (default), \"firefox\", \"google\", \"apple\", \"microsoft\", \"xiaomi\""
				exit 1
			fi
			uci commit kopijahe
			;;
		d)
			multiautologin
			detectwan
			echo "Silahkan masukkan URL halaman landing:"
			read -r "urllanding"
			deteksi=" Location: $urllanding"
			setup
			;;
		f)
			loginfiletxt="$OPTARG"
			login_file
			;;
		h)
			bantuan
			;;
		i)
			install
			;;
		k)
			killkopijahe
			;;
		l)
			loadbalance="$OPTARG"
			advancedmode="true"
			multiautologin
			if [[ "$loadbalance" = "yes" ]] || [[ "$loadbalance" = "no" ]]; then
				uci set kopijahe.@autologin["$multiautologinnum"].loadbalance="$loadbalance"
				uci commit kopijahe
			else 
				echo "hanya menerima jawaban 'yes' atau 'no'"
				exit 1
			fi
			if [[ "$loadbalance" = "yes" ]]; then
				echo "Silahkan tentukan interface yang digunakan (misal: wwan, wwan1):"
				read -r "lbinterface"
				waninterface="$(echo "$lbinterface" | tr -dc "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_")"
				uci set kopijahe.@autologin["$multiautologinnum"].waninterface="$waninterface"
				uci commit kopijahe
			fi
			;;
		m)
			inputmultiautologin="$OPTARG"
			;;
		o)
			advancedmode="true"
			multiautologin
			detectwan
			logout_wifi
			;;
		p)
			password="$OPTARG"
			advancedmode="true"
			multiautologin
			uci set kopijahe.@autologin["$multiautologinnum"].password="$password"
			uci commit kopijahe
			;;
		s)
			seamless_reconnect
			;;
		t)
			testing
			;;
		u)
			username="$OPTARG"
			advancedmode="true"
			multiautologin
			uci set kopijahe.@autologin["$multiautologinnum"].username="$username"
			uci commit kopijahe
			;;
		\?)
			bantuan
			;;
		v)
			wifivariant="$OPTARG"
			advancedmode="true"
			multiautologin
			if [[ "$wifivariant" = "wifi.id" ]] || [[ "$wifivariant" = "@wifi.id" ]] || [[ "$wifivariant" = "wms" ]] || [[ "$wifivariant" = "wms-lite" ]] || [[ "$wifivariant" = "smartbisnis" ]] || [[ "$wifivariant" = "kampus" ]]; then
				uci set kopijahe.@autologin["$multiautologinnum"].wifivariant="$wifivariant"
			else
				echo "Varian jaringan yang didukung:"
				echo "\"wifi.id\", \"wms\", \"wms-lite\", \"kampus\", \"smartbisnis\""
				exit 1
			fi
			if [[ "$wifivariant" = "kampus" ]]; then
				echo "Silahkan masukkan nama kampus anda (misal: \"ut.ac.id\", \"unsiq\", \"trisakti\", \"adibuana\")"
				read -r kampus
				kampus="$(echo "$kampus" | tr -dc "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.")"
				uci set kopijahe.@autologin["$multiautologinnum"].kampus="$kampus"
			fi
			uci commit kopijahe
			;;
		w)
			isleeptime="$OPTARG"
			sleeptime="$(echo "$isleeptime" | tr -dc "0123456789")"
			advancedmode="true"
			multiautologin
			uci set "kopijahe.@autologin[$multiautologinnum].sleeptime=$sleeptime"
			uci commit kopijahe
			;;
		x)
			set -x
			;;
		z)
			advancedmode="true"
			bypassmode="true"
			versi
			multiautologin
			detectwan
			login_wifi
			;; 
		:)
			echo "invalid"
			exit 1
			;;
		*)
			autologin
			;;
	esac
done

# Fungsi autologin
# Deteksi apakah variabel advancedmode hidup, jika tidak, maka lakukan autologin:
while [[ "$advancedmode" = "" ]]; do
	# Cek nomor pengaturan terlebih dahulu
	multiautologin
	# Deteksi antarmuka jaringan yang dipakai
	detectwan
	# Cek kondisi antarmuka jaringan yang dipakai
	deviceclaimfailed
	# Deteksi status koneksi
	captiveportalcheck
	# Cek apakah login sebelumnya diblokir atau tidak
	loginblock
	# Cek pengaturan waktu pengulangan
	sleeptimer
	
	# Jika hasil cek koneksi internet tidak berhasil, maka:
	if [[ "$internetconnected" = "no" ]]; then
		# Cek dulu varian jaringan yang digunakan:
		wifivariant="$(uci -q get kopijahe.@autologin["$multiautologinnum"].wifivariant)"
				
		# Cek apakah IP diblokir,
		# Jika benar, maka:
		if [[ "$ipblocked" = "yes" ]]; then
			# Catat jam dan tanggal saat ini di berkas "/tmp/last.login.$waninterface"
			date > "/tmp/last.login.$waninterface"
			# Catat percobaan login terakhir di berkas "/tmp/last.login.$waninterface"
			echo "Percobaan login terakhir:" >> "/tmp/last.login.$waninterface"
			# Beritahu pengguna bahwa koneksi dengan internet terputus
			echo "Login di interface $waninterface diblokir, alasan: $hasillogin" | tee -a "/tmp/last.login.$waninterface" | logger -t "kopijahe $ver"
			# Logout terlebih dahulu supaya akun tidak tersangkut di server
			logout_wifi
			# Minta penggantian alamat IP
			releaseobtainnewip
		# Cek apakah login diblokir dan tidak menggunakan akun smartbisnis,
		# Jika benar, maka:
		elif [[ "$loginblocked" = "yes" ]] && [[ "$wifivariant" != "smartbisnis" ]]; then
			# Catat jam dan tanggal saat ini di berkas "/tmp/last.login.$waninterface"
			date > "/tmp/last.login.$waninterface"
			# Catat percobaan login terakhir di berkas "/tmp/last.login.$waninterface"
			echo "Percobaan login terakhir:" >> "/tmp/last.login.$waninterface"
			# Beritahu pengguna bahwa koneksi dengan internet terputus
			echo "Login di interface $waninterface diblokir, alasan: $hasillogin" | tee -a "/tmp/last.login.$waninterface" | logger -t "kopijahe $ver"
			# Logout terlebih dahulu supaya akun tidak tersangkut di server
			logout_wifi
			# Minta penggantian alamat IP
			releaseobtainnewip
		# Jika interface tidak terdeteksi atau mendapat kode status cURL 7, maka:
		elif [[ "$kodestatus" = "45" ]] || [[ "$kodestatus" = "7" ]]; then
			# Coba refresh interface terlebih dahulu
			refreshinterface
			# Dan tunggu 3 detik sebelum mencoba kembali
			sleep 3
		# Jika login sebelumnya tidak diblokir, maka:
		else
			login_wifi
			sleep "$sleeptime"
		fi
	else
		# Istirahat sebelum coba mengecek koneksi kembali
		sleep "$sleeptime"
	fi
done